AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - vendor/bundle/**/*

Style/FormatStringToken:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/SpaceInsideRangeLiteral:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false
