AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - vendor/bundle/**/*

Layout/SpaceInsideRangeLiteral:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false

Style/HashSyntax:
  Enabled: false

# TODO

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/MutableConstant:
  Enabled: false
